// Code generated by reset tool; DO NOT EDIT.

package config

func (c *Config) Reset() {
	if c == nil {
		return
	}

	c.RunAddr = ""
	c.FilePath = ""
	c.DBConnStr = ""
	c.KeyH = ""
	c.AuditFilePath = ""
	c.AuditURL = ""
	c.StoreInterval = 0
	c.Restore = false
}

func (c *ConfigAgent) Reset() {
	if c == nil {
		return
	}

	c.HTTPAddr = ""
	c.KeyH = ""
	c.PollInterval = 0
	c.ReportInterval = 0
	c.RateLimit = 0
}
